- hosts: 3.144.31.6 
  vars:
    my_var: raghav
  tasks:
  
  - name: printing  variable value
    debug:
      msg: "{{ my_var }}"
  - name: Install httpd
    yum:
      name: httpd
      state: present 
  - name: Start the httpd service 
    service:
      name: httpd
      state: stopped 

